Merge completed Feature/specs
sebGilR/enumerables pull request #4
Opened 2020-04-07 20:05 UTC by sebGilR

Method specifications were created for all enumerable methods, in a collaborative project.

2020-04-07 21:02 UTC, mosesogwo requested changes
**Hi @sebGilR, @carlosprietobarron:clap:. Great job on your tests :+1:**

- Let's add some additional tests. See my comments on your code.

- Add instruction on how to run tests to your README.


_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if all the items are not nil nor false' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if all the elements are of a given class' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if all items match regular expression' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if any the items is truthy' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if any element is of a given class' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true any item match regular expression' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if none of the items is truthy' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if any element is of a given class' do
Add test for the converse of this case.

2020-04-07 21:02 UTC, mosesogwo commented on spec/main_spec.rb
> +      it 'will return true if none if the items match regular expression' do
Add test for the converse of this case.

2020-04-08 17:57 UTC, shshamim63 commented
## Status :100: Approved :100: 
___
Hi @sebGilR  and @carlosprietobarron :wave: ,
Awesome job :clap: . The project contains the instruction to run the test. And you have covered all the changes asked by the previous reviewer. So nothing is blocking me at this moment. This :+1: is from me. You can go ahead.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-04-08 17:59 UTC, merged